### ISSUE TITLE
A vision for CTOR

### ISSUE THREAD

**Issue by hagane** [codingteam/codingteam.org.ru#35]
Some time ago @ForNeVeR said:
> That site is our HQ, this is out fawking face.

So fscking true. Yet all we have for a face is today's chat logs and a buncha links. There's no reason for anyone to ever visit CTOR, no matter however involved in @codingteam's activities they are. We're a community... No, we are **the** communty, so let's look like one.

So let's have a brainstorm for ideas about making our site more representative of us. I would really like @ForNeVeR, @rexim, @Minoru, @Newlifer and @gsomix to take part, though all @codingteam/members are free to suggest anything.

I'll collate and present the results next week, at May 21

**Comment by ForNeVeR** [comment]
> There's no reason for anyone to ever visit CTOR, no matter however involved in @codingteam's activities they are.

That's not completely right. I'm visiting there from time to time for exactly the purpose of viewing the logs in case I missed something.

But I agree that we could place the logs somewhere outside of our main page and that the discussion is necessary.

**Comment by hagane** [comment]
Thanks for correcting me, @ForNeVeR . Of course the logs shouldn't go FOAD, they're integral to what we do and how we do it.

I'd also like to suggest having an unified feed of blog posts, tweets and whatever.

**Comment by ForNeVeR** [comment]
I should note that we have a bunch of various projects that should one day be used on our site. I personally work on https://github.com/ForNeVeR/yog-sothoth that will provide an API for real-time and reliable log management.

@Minoru also works on https://github.com/codingteam/Gestalt that will provide an API for querying various GitHub statistics regarding our team.

At the first step I'd like to see something like http://fsprojects.github.io/ at least. And, by the way, we could (easily?)integrate the same code that manages that site.

**Comment by IngvarJackal** [comment]
FYI: I suspended work on desktop client https://github.com/IngvarJackal/ctor-view waiting for @Minoru 's Gestalt API and running instance/stub.

**Comment by Minoru** [comment]
Whoa, Gestalt is blocking a lot of stuff all of a sudden! Sorry about that. No promises yet, though.

How come @rexim's streams weren't mentioned? I know not everybody in the community watch them or even agree with the idea, but Mixer claimed he do them primarily for Codingteam.

Separate page for our attempts at ICFPC might be in order.

Overall, I believe logs and GitHub statistics are top priority because these things are most representative of Codingteam as a whole. Everything else is just details, things that a few Codingteamers happen to do.

**Comment by rexim** [comment]
I think logs and GitHub statistics are enough for now.

**Comment by ForNeVeR** [comment]
Well, that would be good to mention @rexim streams or even add Twitter stream of `@tsoding` too. Good that you mentioned that.

**Comment by aman7** [comment]
and we should something like reminder for streaming, which will keep
reminding team members about upcoming stream. and we need more streamers on
different languages

**Comment by IngvarJackal** [comment]
How about RSS with streams?

**Comment by aman7** [comment]
or add feature to bot, which will keep sending private message to team
members

**Comment by IngvarJackal** [comment]
Also, probably it would be good idea to centralize processes and responsibilities related to community infrastructure instead of developing and maintaining separately by @ForNeVeR or @rexim and others.
E.g. create [developer/QA/release/admin] teams with responsibility management and centralized hosting system for Loglist, CTOR home page and horta-hell because such critical systems are crucial for community connectivity.
That structures of community members would become springboards for Log, RSS, Gestalt and other subsystems' deployment in near future.

**Comment by Minoru** [comment]
I can't agree. As far as I understand the current situation, we already 
have two people with root access to all of Codingteam's infrastructure 
(Rexim and ForNeVeR), which, in my opinion, is quite enough. Including 
more people might give us more resilience (what if Syberia goes offline? 
:), but it will also incur more synchronization costs. IMO, now worth 
it.

"Release" team is totally unnecessary as we aren't productive enough to 
warrant its existence (in my view, at least. ForNeVeR, who is the 
current release team, might disagree.)

QA? What's that? Don't we test in production? In all seriousness, 
though, it doesn't seem that we have QA people in Codingteam, so whom 
would you put into that team? Developers who would rather write code?

Overall, I don't think we're big enough of a community to benefit from 
a more rigid structure.

**Comment by hagane** [comment]
@Minoru is right. I too think that having a rigid structural organization would be a detriment.

**Comment by ForNeVeR** [comment]
Such restructurization is definitely out of scope of this task btw.

**Comment by hagane** [comment]
All right, I believe that everyone willing to share their opinion have done so.

As it stands, the most desired feature is a showcase of our projects, with github stats for each of them. The support for that feature is overwhelming. That's obviously what we should focus on in the upcoming (re)development. The @codingteam has spoken.
